from enum import Enum

class UserRoleEnum(Enum):
    ADMIN = 'ADMIN'
    DATA_OWNER = 'DATA_OWNER'
    DATA_STEWARD = 'DATA_STEWARD'
    SPONSOR = 'SPONSOR'
    PERMANENT_CONTROL = 'PERMANENT_CONTROL'
    MANAGEMENT_CONTROL = 'MANAGEMENT_CONTROL'

class AppModuleEnum(Enum):
    USERS = 'USERS'
    CONNECTORS = 'CONNECTORS'
    REFERENCES = 'REFERENCES'
    DICTIONARIES = 'DICTIONARIES'
    POPULATIONS = 'POPULATIONS'
    DOMAINS = 'DOMAINS'
    SUB_DOMAINS = 'SUB_DOMAINS'
    RULES = 'RULES'
    ISSUE_TRACKER = 'ISSUE_TRACKER'
    REMEDIATION_ACTIONS = 'REMEDIATION_ACTIONS'
    AUDIT_LOG = 'AUDIT_LOG'

class UserActionEnum(Enum):
    READ = 'READ'
    WRITE = 'WRITE'
